// Time complexicity of searching a word in trie is O(L) which is equal to the length of a word

// This data structure is used when we have to search a word of string when so many words are given

// This tree root have many childeren it is not like binary tree ,because of having many childeren this is huge tree

//root is an empty node

// we mark end after formation of each word

// prefix is not repeated